services:
  db:
    image: postgres:16
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 2s
      timeout: 2s
      retries: 30
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8000"
    volumes:
      - media_data:/service_app/static

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - media_data:/static

volumes:
  pgdata:
  media_data: