server {
    listen 80;

    # Фронт
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Медиа
    location /static/ {
        alias /usr/share/nginx/static/;
        autoindex off;
    }

    # API
    location /api/ {
        proxy_pass http://app:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_set_header X-Forwarded-Proto $scheme;
    }
}